version: '3.8'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80" # Host port changed to 8081
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel_db
            - DB_USERNAME=laravel_user
            - DB_PASSWORD=laravel_password

    db:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_password
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
